In [1]:
import torch
import torch.nn as nn

In [2]:
def get_log_probabilities(probs_of_0):
    """
    Convenience function...
    """
    return torch.log(torch.tensor([probs_of_0, 1.0 - probs_of_0]))

I'm only using "sum" here just because it is slightly easier to see what's going on.

In [9]:
nll = nn.NLLLoss(reduction="sum")
lp = get_log_probabilities(0.98)
print(lp)
nll(lp.unsqueeze(0), torch.tensor([0]))

tensor([-0.0202, -3.9120])


tensor(0.0202)

In [11]:
nll = nn.NLLLoss(reduction="sum")
lp = get_log_probabilities(0.98)
print(lp)
nll(torch.stack([lp, lp]), torch.tensor([0, 0]))

tensor([-0.0202, -3.9120])


tensor(0.0404)

Ignore index is saying--hey if the correct class in the Target has an id as the input to `ignore_index`, then don't use that in the loss.

In [6]:
nll = nn.NLLLoss(reduction="sum", ignore_index=0)
probs_of_0 = 0.99
lp = get_log_probabilities(probs_of_0)
print(lp)
# unsqueeze at 0 because the first dimension has to be batch size
print(nll(lp.unsqueeze(0), torch.tensor([0])))

tensor([-0.0101, -4.6052])
tensor(0.)
