In [1]:
import torch

In [25]:
a = torch.ones(2, 3); a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
b = 2 * torch.ones(2, 3)

In [36]:
a.size()

torch.Size([2, 3])

In [34]:
c = torch.stack([a, b], dim=0); print(c); print(c.size())

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])
torch.Size([2, 2, 3])


In [31]:
c = torch.stack([a, b], dim=1); print(c); print(c.size())

tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]]])

In [35]:
c = torch.stack([a, b], dim=2); print(c); print(c.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[1., 2.],
         [1., 2.],
         [1., 2.]]])
torch.Size([2, 3, 2])
